[tool.poetry]
name = "posit-bakery"
version = "0.1.0"
description = "Tools for extracting and manipulating bake artifacts for various commands"
authors = ["Ian H. Pittwood <ian.pittwood@posit.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.5"

[tool.poetry.scripts]
bakery = "posit_bakery.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
