[tool.poetry]
name = "posit-bakery"
version = "0.2.0-dev"
description = "Tools for extracting and manipulating bake artifacts for various commands"
authors = ["Ian H. Pittwood <ian.pittwood@posit.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
bakery = "posit_bakery.main:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"
jinja2 = "^3.1.4"
rich = "^13.8.1"
python-hcl2 = "^4.3.5"
gitpython = "^3.1.43"
tomlkit = "^0.13.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.0"

[tool.ruff]
line-length = 120
fix = true
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
