name: Test build-test-push action

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-build-test-push:
    name: Test action works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run build-test-push
        uses: ./build-test-push
        with:
          bake-files: ''
