name: Issue Automation
on:
  issues:
    types:
      - opened

jobs:
  issue:
    # only run in posit-dev/images-shared.
    if: github.repository == 'posit-dev/images-shared'
    runs-on: ubuntu-latest
    steps:

      - name: GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Add to Platform Carbon Project
        uses: actions/add-to-project@v1.0.2
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          project-url: https://github.com/orgs/posit-dev/projects/17

      - name: Add Default Labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          labels: |
            docker
